--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2024-09-19 11:32:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 329893)
-- Name: invoice; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA invoice;


ALTER SCHEMA invoice OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 329909)
-- Name: customer; Type: TABLE; Schema: invoice; Owner: postgres
--

CREATE TABLE invoice.customer (
    id bigint NOT NULL,
    sync_time timestamp with time zone NOT NULL,
    customer_name text NOT NULL,
    address text NOT NULL,
    phone text NOT NULL,
    emai text NOT NULL
);


ALTER TABLE invoice.customer OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 329908)
-- Name: customer_id_seq; Type: SEQUENCE; Schema: invoice; Owner: postgres
--

ALTER TABLE invoice.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME invoice.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 330069)
-- Name: invoice_details; Type: TABLE; Schema: invoice; Owner: postgres
--

CREATE TABLE invoice.invoice_details (
    id bigint NOT NULL,
    sync_time timestamp with time zone NOT NULL,
    customer_name text NOT NULL,
    customer_address text NOT NULL,
    customer_phone text NOT NULL,
    customer_email text NOT NULL,
    product_name text NOT NULL,
    quantity text NOT NULL,
    price text NOT NULL,
    tax text NOT NULL,
    total_price text NOT NULL,
    sub_total text,
    status text
);


ALTER TABLE invoice.invoice_details OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 330068)
-- Name: invoice_details_id_seq; Type: SEQUENCE; Schema: invoice; Owner: postgres
--

ALTER TABLE invoice.invoice_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME invoice.invoice_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 329895)
-- Name: products; Type: TABLE; Schema: invoice; Owner: postgres
--

CREATE TABLE invoice.products (
    id bigint NOT NULL,
    sync_time timestamp with time zone NOT NULL,
    product_name text NOT NULL,
    description text NOT NULL,
    price text NOT NULL
);


ALTER TABLE invoice.products OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 329894)
-- Name: products_id_seq; Type: SEQUENCE; Schema: invoice; Owner: postgres
--

ALTER TABLE invoice.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME invoice.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3335 (class 0 OID 329909)
-- Dependencies: 218
-- Data for Name: customer; Type: TABLE DATA; Schema: invoice; Owner: postgres
--

COPY invoice.customer (id, sync_time, customer_name, address, phone, emai) FROM stdin;
2	2024-06-07 18:56:16.688782+05:30	user1	abcd	12598323	user1@gmail.com
1	2024-06-07 18:56:16.688782+05:30	user2	yruw hieuowupip klw,gueyiw,ny	45555555	vvmm@gmail.com
3	2024-06-18 12:09:26.881057+05:30	user3	yitreo iopwq kjdoeio,poppwip	12356997	user3@gmail.com
\.


--
-- TOC entry 3337 (class 0 OID 330069)
-- Dependencies: 220
-- Data for Name: invoice_details; Type: TABLE DATA; Schema: invoice; Owner: postgres
--

COPY invoice.invoice_details (id, sync_time, customer_name, customer_address, customer_phone, customer_email, product_name, quantity, price, tax, total_price, sub_total, status) FROM stdin;
9	2024-06-17 19:26:24.503669+05:30	user1	abcd	12598323	user1@gmail.com	product1,product2	2,1	12.00,12.00	3.6	39.6	36.0	Paid
10	2024-06-18 11:25:10.69763+05:30	user1	abcd	12598323	user1@gmail.com	product2,product3	1,2	12.00,234.00	48.0	528.0	480.0	Paid
\.


--
-- TOC entry 3333 (class 0 OID 329895)
-- Dependencies: 216
-- Data for Name: products; Type: TABLE DATA; Schema: invoice; Owner: postgres
--

COPY invoice.products (id, sync_time, product_name, description, price) FROM stdin;
1	2024-06-07 18:18:13.138527+05:30	product1	wew	12
2	2024-06-07 18:21:36.126537+05:30	product2	gtrh	12
3	2024-06-07 18:22:25.71996+05:30	product3	frfreer	234
4	2024-06-07 18:28:08.81159+05:30	product4	fgd	56
5	2024-06-07 18:28:28.638523+05:30	product5	fgd	56
6	2024-06-07 18:28:42.852634+05:30	product6	fgd	56
7	2024-06-07 18:37:50.219539+05:30	product7	rrg	34
8	2024-06-12 14:54:00.299545+05:30	product8	huri jewow ekjkjwl	500
10	2024-06-17 19:31:52.872875+05:30	product_3	uiuorl fjkjkfl;s skdll elw;	256
20	2024-06-18 12:04:29.139589+05:30	product_15	ewr	670
\.


--
-- TOC entry 3343 (class 0 OID 0)
-- Dependencies: 217
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: invoice; Owner: postgres
--

SELECT pg_catalog.setval('invoice.customer_id_seq', 5, true);


--
-- TOC entry 3344 (class 0 OID 0)
-- Dependencies: 219
-- Name: invoice_details_id_seq; Type: SEQUENCE SET; Schema: invoice; Owner: postgres
--

SELECT pg_catalog.setval('invoice.invoice_details_id_seq', 10, true);


--
-- TOC entry 3345 (class 0 OID 0)
-- Dependencies: 215
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: invoice; Owner: postgres
--

SELECT pg_catalog.setval('invoice.products_id_seq', 21, true);


--
-- TOC entry 3187 (class 2606 OID 329915)
-- Name: customer customer_id_pkey; Type: CONSTRAINT; Schema: invoice; Owner: postgres
--

ALTER TABLE ONLY invoice.customer
    ADD CONSTRAINT customer_id_pkey PRIMARY KEY (id);


--
-- TOC entry 3189 (class 2606 OID 330075)
-- Name: invoice_details invoice_details_id_pkey; Type: CONSTRAINT; Schema: invoice; Owner: postgres
--

ALTER TABLE ONLY invoice.invoice_details
    ADD CONSTRAINT invoice_details_id_pkey PRIMARY KEY (id);


--
-- TOC entry 3185 (class 2606 OID 329901)
-- Name: products invoice_id_pkey; Type: CONSTRAINT; Schema: invoice; Owner: postgres
--

ALTER TABLE ONLY invoice.products
    ADD CONSTRAINT invoice_id_pkey PRIMARY KEY (id);


-- Completed on 2024-09-19 11:32:56

--
-- PostgreSQL database dump complete
--

